version: '3'
services:
  core-service:
    build: ./core-service
    ports:
      - "3000:3000"
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - core-service
      - user-service
      - product-service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
